# Site settings
title: Grant McConnaughey
email: grantmcconnaughey@gmail.com
description: "My name is Grant McConnaughey. I'm a software developer specializing in Python, Django, Vue.js, and AWS. I lead software teams and mentor others to become leaders themselves."
baseurl: ""
url: "http://grantmcconnaughey.com/"
username: grantmcconnaughey
timezone: America/Chicago

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
