# Site settings
title: Grant McConnaughey
email: grantmcconnaughey@gmail.com
description: "Grant McConnaughey is a Full-Stack Web Developer specializing in Python, Django, JavaScript, jQuery, HTML, and CSS. He loves making sites that are beautiful, usable, and robust."
baseurl: ""
url: "http://grantmcconnaughey.com/"
username: grantmcconnaughey
timezone: America/Chicago

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
