# Site settings
title: Grant McConnaughey
email: grantmcconnaughey@gmail.com
description: "Full-Stack Web Developer specializing in Python, Django, Groovy, Grails, SQL, jQuery, HTML, and CSS. Focused on the unachievable goal of learning everything there is to know. Loves making sites that are beautiful, usable, and robust."
baseurl: ""
url: "http://grantdev.com/"
username: grantmcconnaughey
timezone: America/Chicago

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
